support for terraform 0.13
BerlingskeMedia/bm.terraform-module.ecs pull request #10
Opened 2020-10-30 14:32 UTC by Maciej-Gierwatowski

2020-12-07 12:10 UTC, bmwosz commented
AFAIK we wanted to close this PR without merging to not work with already depricated stuff

2020-12-07 12:19 UTC, bmtoml requested changes

2020-12-07 12:19 UTC, bmtoml commented on main.tf
> +  source      = "git@github.com:BerlingskeMedia/bm.terraform-module.security?ref=production"
" we are not, In 12 PR there is no production tag in main.tf file"

ghosts then?

2021-06-21 12:20 UTC, bmtoml requested changes
maciej, close this?

2021-09-07 09:42 UTC, wszychta commented
This PR is useless for us now.

2021-09-07 09:42 UTC, closed without merging