DATA-1513| Use context module
BerlingskeMedia/bm.terraform-module.ecs pull request #49
Opened 2023-05-24 13:22 UTC by BM-hali

2023-06-06 10:57 UTC, Maciej-Gierwatowski requested changes
Please add `CHANGELOG.md` entry and update `README.md`

2023-06-06 10:57 UTC, Maciej-Gierwatowski commented on context.tf
> +variable "launch_type" {
This value has to be defaulted to "FARGATE" somewhere. Otherwise ecs-services won't work. At least not without breaking change in configuration

2023-06-06 10:57 UTC, Maciej-Gierwatowski commented on main.tf
>  }
This module still relies on values from direct variables, instead of input context

2023-06-06 10:57 UTC, Maciej-Gierwatowski commented on main.tf
>  }
This module still relies on values from direct variables, instead of input context

2023-06-07 07:21 UTC, BM-hali commented on context.tf
> +variable "launch_type" {
Okay, I will update the default value to FARGATE

2023-06-07 07:24 UTC, BM-hali commented on context.tf
> +variable "launch_type" {
And good catch!

2023-06-07 11:14 UTC, BM-hali commented on main.tf
>  }
Done

2023-06-07 11:14 UTC, BM-hali commented on main.tf
>  }
Done

2023-06-07 11:14 UTC, BM-hali commented
> Please add `CHANGELOG.md` entry and update `README.md`

Did updates as discussed 🙂

2023-06-13 12:44 UTC, Maciej-Gierwatowski requested changes

2023-06-13 12:44 UTC, Maciej-Gierwatowski commented on CHANGELOG.md
> +- Use input context variable to fetch settings, overridable by setting local variables [[DATA-1513]](https://berlingskemedia.atlassian.net/browse/DATA-1513?atlOrigin=eyJpIjoiMDExNDRhNzI1OTU1NDQ3ZDljY
I think query part (`?...`) is redundant in url ;)

2023-06-13 12:44 UTC, Maciej-Gierwatowski commented on README.md
> +  source          = "git@github.com:BerlingskeMedia/bm.terraform-module.ecs?ref=tags/1.21.2"
I'd change query to: `?ref=X.Y.Z` to not suggest any particular version

2023-06-13 12:44 UTC, Maciej-Gierwatowski commented on main.tf
>    subnet_ids                                      = var.public_subnets
from context

2023-06-26 09:47 UTC, BM-hali commented on main.tf
>    subnet_ids                                      = var.public_subnets
Updated now :)

2023-06-27 11:04 UTC, Maciej-Gierwatowski approved these changes

2023-06-28 08:33 UTC, BM-hali commented on CHANGELOG.md
> +# 1.21.2
I updated the CHANGELOG but I would like to challenge the need for that file a bit. Since we are using Git release tags you can just follow the changes there? As far as I can see there is no additional information in the CHANGELOG

2023-07-06 06:48 UTC, Maciej-Gierwatowski approved these changes

2023-07-06 07:20 UTC, merged